### ISSUE TITLE
Tracks does not start on ubuntu 16.04

### ISSUE THREAD

**Issue by franciscorichter** [Soundnode/soundnode-app#982] opened 2017-04-20 09:43 UTC
I just installed the app on my desk computer with ubuntu 16.04. Everything goes well, but when I press play the sound does not start at all. If I try to forward it I got a small message saying that something went wrong. It happens with all songs.

**Comment by wb9688** [comment] 2017-04-20 10:16
This is yet another duplicate of #802, where I've also posted a temporary
solution.

**Closed** 2017-04-24 16:21 UTC
