### ISSUE TITLE
Can't play anything (audio)

### ISSUE THREAD

**Issue by mcast-ns** [Soundnode/soundnode-app#973] opened 2017-03-29 15:33 UTC
When I hit any record to be played, it is showed at the bottom bar and the play/stop button changes, but it never plays the song!!!

I've a Mac mid 2015, MBPro 15

**Comment by Poltergeist** [comment] 2017-03-29 15:43
It probably has to do with this:
> Be aware that Soundnode relies on Soundcloud API which only allowing third party apps to play 15 thousand tracks daily. When the rate limit is reached all users aren't able to play any song until the end of the current day the limit was reached.

**Comment by wb9688** [comment] 2017-03-29 15:52
This is yet another duplicate of #802, where I've posted a temporary
solution.

**Closed** 2017-03-29 17:47 UTC
