### ISSUE TITLE
Nothing plays

### ISSUE THREAD

**Issue by iYatsumi** [Soundnode/soundnode-app#974] opened 2017-03-29 22:41 UTC
i used soundnode before and it was working great so i decided to install it on my laptop, but whenever i try to play a track it doesn't do anything, i have verify that my internet is on but that wasn't the issue.

**Comment by iYatsumi** [comment] 2017-03-29 22:44
similar to the top comment problem with the track here 
https://www.youtube.com/watch?v=yvZdH6w5l58

**Comment by wb9688** [comment] 2017-03-30 04:35
This is yet another duplicate of #802.

@weblancaster: Can we do anything against duplicate issues?

**Comment by weblancaster** [comment] 2017-03-30 20:26
@wb9688 we close duplicates and continue the discussion on the original issue, that's it.

**Closed by weblancaster** 2017-03-30 20:26 UTC
