### ISSUE TITLE
Getting error - "Use of const in strict mode" after latest pull.

### ISSUE THREAD

**Issue by Ajeey** [Soundnode/soundnode-app#695] opened 2016-03-26 14:41 UTC
Debugged and found out the line causing that  - const SONG_TIMEOUT_THRESHOLD = 3;

Whats the fix though ?

**Comment by jakejarrett** [comment] 2016-03-27 01:44
@Ajeey where does this error occur? I'm unable to reproduce (Just playing songs & restarting some songs)

**Comment by dgattey** [comment] 2016-04-21 01:31
Don't think this is an issue in the latest?

**Comment by weblancaster** [comment] 2016-04-25 21:17
I haven't seen this issue when opening the app.. for that reason closing this issue.

**Closed by weblancaster** 2016-04-25 21:17 UTC
