### ISSUE TITLE
Something went WRONG ! can't play tracks :(

### ISSUE THREAD

**Issue by SghaierFiras** [Soundnode/soundnode-app#1002] opened 2017-07-18 08:26 UTC
Since I've installed Soundnode on my PC, it didn't play any track for me and always shows that red alert for me saying that something went wrong and it can(t play the track, and that is for all tracks.
I'm using Ubuntu 16.04 !

![screenshot from 2017-07-18 09-21-08](https://user-images.githubusercontent.com/16582284/28307522-15a853ea-6b9b-11e7-9c27-0aa0be362ef5.png)

**Comment by wb9688** [comment] 2017-07-18 17:51
This is yet another duplicate of #802. You can also find my temporary
solution there.

**Comment by weblancaster** [comment] 2017-07-19 21:07
Besides the info @wb9688 gave, past release of Soundnode was released with a bug that is now fixed but not released yet.

**Closed by weblancaster** 2017-07-19 21:07 UTC
