### ISSUE TITLE
timeline clicks are ignored in osx

### ISSUE THREAD

**Issue by nazikus** [Soundnode/soundnode-app#890] opened 2016-10-09 14:27 UTC
cannot skip track to certain time by clicking on the timeline. Clicks are simply ignored and nothing happens.

OSX 10.11.6 x64
soundnode 0.6.5 build

**Comment by weblancaster** [comment] 2016-10-10 15:14
@nazikus correct, this is no a feature yet.

**Comment by bryguy** [comment] 2016-11-09 16:48
Dupe of #847, no?

**Comment by weblancaster** [comment] 2016-11-09 22:17
yep, it's a dupe.. thanks @bryguy and this can be closed now.

**Closed by weblancaster** 2016-11-09 22:17 UTC
Labels: feature
