### ISSUE TITLE
Failed [Native media keyboard shortcuts] Linux

### ISSUE THREAD

**Issue by ronaldoats** [Soundnode/soundnode-app#488] opened 2016-01-12 22:30 UTC
Failed in Linux.
Manjaro 
Linux lnxSMJ 4.2.8-1-MANJARO #1 SMP PREEMPT Tue Dec 15 08:34:13 UTC 2015 x86_64 GNU/Linux
Desktop --> Cinnamon 2.8.6

**Comment by nebulade** [comment] 2016-01-19 15:02
Duplicate of #445

**Closed** 2016-01-26 22:30 UTC
