### ISSUE TITLE
"Oh no, Something went wrong, I cant play this track"

### ISSUE THREAD

**Issue by mani-zaeim** [Soundnode/soundnode-app#929] opened 2016-12-19 02:39 UTC
I am not sure this problem is mine or not, but I can not play anything, and I got the message **"Oh no, Something went wrong, I cant play this track"**, Im running it on _ArchLinux and in console nothing is shown_ and I dont know how can i turn on **the debuge mode**.

**Comment by Legitgamer264** [comment] 2016-12-19 02:42
Did you build it from the source or from the .zip file from the website?

**Comment by mani-zaeim** [comment] 2016-12-19 02:58
no, I use the aur (Archlinux repository)
https://aur.archlinux.org/packages/soundnode/
but I can not get any error message on console, even when I run it on console. is there any way to debug this issue ?!

Thanks.

**Comment by Legitgamer264** [comment] 2016-12-19 03:24
If you build it with the source, you can get around the API limit by running a python script and putting the access token and client ID that the script puts out into soundnode. But if you don't build it with the source, then you have to wait until the API limit resets. When we reach the limit of 15K tracks per day then you can't play any more until the API limit resets

**Comment by weblancaster** [comment] 2016-12-19 06:32
@mani-zaeim the current version for Linux was released with a bug that was fixed already but we haven't released a new version yet because a bunch of improvement is coming.

**Comment by mani-zaeim** [comment] 2016-12-19 06:45
@Legitgamer264 Thanks for your information regarding python script.
@weblancaster thanks for your information and great news on Linux version, that will be really exiting

**Comment by Legitgamer264** [comment] 2016-12-19 06:47
@mani-zaeim Here is the comment with the python script - https://github.com/Soundnode/soundnode-app/issues/802#issuecomment-261705999. Look down a little. Hopefully running this will fix the issue

**Comment by alexandrekotob** [comment] 2017-02-02 17:19
Hello, just discover this app. 
Downloaded the app mac from website. Same message when I try to play a song.

**Comment by Zieg** [comment] 2017-02-11 08:26
It seems like the issue is not with an app itself. This is due to Soundcloud API that has a limit of playing 15K tracks per day.

**Comment by weblancaster** [comment] 2017-04-07 23:06
this is a duplicated of #802

**Closed by weblancaster** 2017-04-07 23:06 UTC

**Comment by czerwinski76** [comment] 2019-04-21 07:16
It's not à 15K issue. Use Auryo !😀.
https://auryo.com/
