### ISSUE TITLE
JavaScript Error when login without ROOT permissions

### ISSUE THREAD

**Issue by acrox999** [Soundnode/soundnode-app#989] opened 2017-05-26 07:22 UTC
The following error is produced when trying to login:

```
Uncaught Exception:
Error: EACCES: permission denied, open '/opt/soundnode-git/resources/app/app/public/js/system/userConfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:178:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at setUserData (/opt/soundnode-git/resources/app/main.js:74:6)
    at WebContents.contents.on (/opt/soundnode-git/resources/app/main.js:68:5)
    at emitMany (events.js:127:13)
    at WebContents.emit (events.js:201:7)
```

The best way to avoid this is probably by making Soundnode saves the config file in the user's `$HOME` directory.

---

**How to reproduce:**
1. Install the app from AUR (soundnode-git)
2. Run the app
3. Login

**How to work around this issue:**
1. Run the app as root

---

OS: `Arch Linux x86_64 (Kernel version: 4.11.2)`
Soundnode version: `git revision 4f4842624f738f51bd7f0d2dc8b32eae88e75335`

**Comment by wb9688** [comment] 2017-05-26 08:15
Does it work after you've done `sudo chmod a+r /opt/soundnode-git`? If so,
it's the fault of the maintainer of that AUR package and you should contact
him.

**Comment by acrox999** [comment] 2017-05-26 09:46
I will try that. Thanks.

It seems that the maintainer has bailed out since npm is too heavy for his
computer to handle.

If your suggestion works, I will update the package myself.

**Comment by jakejarrett** [comment] 2017-06-05 21:58
The problem is that the config file for soundnode is in a folder you don't have write permissions to, Will try & fix this by ensuring *nix systems use the proper config folders (`$HOME/.config/soundnode/` or `$XDG_CONFIG_HOME/soundnode` on linux systems)

**Comment by weblancaster** [comment] 2017-07-19 21:44
#991 was merged with that we can close this issue.

**Closed by weblancaster** 2017-07-19 21:44 UTC
