### ISSUE TITLE
Option to hide Windows 10 Notification on changing Song

### ISSUE THREAD

**Issue by Scarwolf** [Soundnode/soundnode-app#381] opened 2015-09-19 20:39 UTC
I am using Windows 10 and a Mouse with Media Keys. If I press the "Next Song" button for example 5 times, it shows me every song between as a notification, so the last one disappears after approx. 15 Secs (3 Sec/Song)

**Comment by jakejarrett** [comment] 2015-09-20 02:18
Duplicate of #306, this feature is being looked into currently.

**Closed** 2015-09-22 22:09 UTC
