### ISSUE TITLE
Cannot play any track

### ISSUE THREAD

**Issue by Legitgamer264** [Soundnode/soundnode-app#915] opened 2016-11-26 23:14 UTC
whenever I try to play a track I get "Something went wrong. I can't play this track".

**Comment by wb9688** [comment] 2016-11-27 10:57
If you've Python 2 installed and use SoundCloud with username/password login, you could try running the script in [my comment](https://github.com/Soundnode/soundnode-app/issues/802#issuecomment-261705999), copy the Client ID and Access Token it returns, open Soundnode, press Ctrl+/, type `localStorage.scClientId = 'insert_client_id'; localStorage.scAccessToken = 'insert_access_token'` and restart Soundnode.

Btw this is yet another duplicate of #802…

**Comment by Legitgamer264** [comment] 2016-11-27 18:39
I will give that a try. Thank you! Do you know where I could get access to pre-release versions of soundnode?

**Comment by Legitgamer264** [comment] 2016-11-27 21:05
I am getting "import requests, no such module named requests"

**Comment by c1n1k** [comment] 2016-11-28 08:10
a have problem like this after installation on my PC (win10, x64) it works but next day it don' work

**Comment by ChristopherNeuwirth** [comment] 2016-11-28 09:24
Guess it's the same issue as here: https://github.com/Soundnode/soundnode-app/issues/910

**Closed** 2017-01-11 16:29 UTC
