### ISSUE TITLE
Section "Discover"

### ISSUE THREAD

**Issue by luntegg** [Soundnode/soundnode-app#947] opened 2017-01-31 13:07 UTC
https://soundcloud.com/discover

This section doesn't exist in app now.

**Comment by wb9688** [comment] 2017-01-31 13:26
This is a duplicate of #797

**Comment by luntegg** [comment] 2017-01-31 13:30
Sorry, I've searched but not found.

**Comment by weblancaster** [comment] 2017-01-31 15:43
you can comment over there if need anything else @luntegg

**Closed by weblancaster** 2017-01-31 15:43 UTC
