### ISSUE TITLE
Missing tracks

### ISSUE THREAD

**Issue by Spaisekraft** [Soundnode/soundnode-app#667] opened 2016-03-06 00:19 UTC
There are missing tracks for the artist "dark cat" (soundcloud.com/dark_cat/).

**Comment by jakejarrett** [comment] 2016-03-06 01:05
Duplicate of #630 

Some of the tracks aren't listed as playable for third party services (EG/ Soundnode)

**Closed by jakejarrett** 2016-03-06 01:05 UTC
