### ISSUE TITLE
Stuck at "Authentificating your Soundcloud account" when developing locally

### ISSUE THREAD

**Issue by Avishai2112** [Soundnode/soundnode-app#524] opened 2016-01-26 03:18 UTC

**Comment by jakejarrett** [comment] 2016-01-26 03:37
Is this a build from the website & which operating system are you using?

**Comment by weblancaster** [comment] 2016-01-26 03:44
what option you tried to login.. `facebook` or `google` or `soundcloud account`

**Comment by Avishai2112** [comment] 2016-01-26 07:21
Hi, ya its the Windows build from the website ; i mean i didn't get any form to choose an option or anything about the connection to my soundcloud ... everytime i launch the exe file i stuck in the loading screen "Authenticating your soundcloud account"

**Comment by daxlab** [comment] 2016-01-26 17:45
Me too facing same issue. Tried both building from source and website one. Linux 64 bit (Ubuntu). Node version 5.5.0

**Comment by weblancaster** [comment] 2016-01-26 17:53
Are you inside a private network? can you access Soundcloud from the same network.

**Comment by daxlab** [comment] 2016-01-26 18:01
Yes, I can access Soundcloud in browser. What I did was re-clone the repo in a different directory and reinstall from there, and the opens and asks for authentication but when I click on google account nothing happens.

**Comment by Pitros** [comment] 2016-01-26 19:15
@daxlab can you open dev tools (probably shortcut (`ctrl + /`) isn't working at that moment) so you would need to edit `package.json` and set `toolbar` to `true` and then give some info what shows up in console?

**Comment by daxlab** [comment] 2016-01-26 19:41
@Pitros 
![image](https://cloud.githubusercontent.com/assets/6784159/12592323/fc6d5bb6-c491-11e5-9aaf-f4fac0bb6701.png)

then I did, ```npm install async```

![image](https://cloud.githubusercontent.com/assets/6784159/12592454/6f69db12-c492-11e5-8a7f-4f17336e6f8d.png)

```npm install underscore``` doesn't make any difference.

**Comment by jakejarrett** [comment] 2016-01-26 19:50
Which node/npm version are you running? I'm pretty sure npm v3 installs all dependencies to the one folder which will cause a bunch of dependencies to be missing.

**Comment by Pitros** [comment] 2016-01-26 19:53
There might be an issue with `universal-analytics`, can you update node and npm to latest version and reinstall/rebuild `universal-analytics`. If that wont help, can you comment out some lines:
in: `app/public/js/system/settings.js` 
```3: var ua = require('universal-analytics');```

and in `app/public/js/app.js`
```
96: window.settings.visitor.pageview("/").send();
111: window.settings.visitor.pageview("/").send();
113: window.settings.visitor.pageview(toState.name).send();
```
And post the results.

**Comment by daxlab** [comment] 2016-01-26 19:56
node version : 5.5.0  and npm : 3.5.3

**Comment by daxlab** [comment] 2016-01-26 20:01
@Pitros after commenting above mentioned line, the app is working fine.

![image](https://cloud.githubusercontent.com/assets/6784159/12593132/862df150-c495-11e5-8c17-100744ae951f.png)

**Comment by Avishai2112** [comment] 2016-01-26 22:24
After a source build its working fine for me, now i'm getting the "Connect with Soundcloud" window.

**Comment by Pitros** [comment] 2016-01-26 22:29
I would keep that open, @Avishai2112 did you just do a clean build (npm install etc.) and it started working, or you did something more?

**Comment by chocnut** [comment] 2016-01-27 04:58
I can confirm, I'm using OSX El Capitan the popup window for sound cloud is not showing up.

**Comment by gkov** [comment] 2016-01-27 17:47
Experienced this on filtered network where http://soundcloud.com/ would be filtered by websense however httpS://soundcloud.com/ was just fine.

**Comment by daxlab** [comment] 2016-02-08 21:01
the problem still persists.

**Comment by Recydywa** [comment] 2016-02-28 13:35
I have this problem. 

I've tried the Linux version 0.6.2 downloaded from website on Xenial (development version of Ubuntu, in April it will become 16.04 LTS).

Also I would like to know what are dependencies of this app if there are any. I know that for building you need Node.js and other things. But do I need this also for the precompiled version. If yes than I wonder why they aren't listed anywhere. How the user is supposed to know about such requierements.

**Comment by wb9688** [comment] 2016-02-28 13:40
There are no runtime dependencies (except a few on Linux, eg. X11, but you
should have them)
Op 28 feb. 2016 14:35 schreef "Recydywa" <notifications@github.com>:

**Comment by jakejarrett** [comment] 2016-02-28 13:52
gconf appears to be a dependency for all nwjs apps on linux.

Building, you only need the dependencies listed on the [Wiki](https://github.com/Soundnode/soundnode-app/wiki/Development)

**Comment by wb9688** [comment] 2016-02-28 15:04
A fast enough processor is also required :smile:, because I get a
`segmentation fault` on my netbook with a 700 MHz processor...
Op 28 feb. 2016 14:52 schreef "Jake Jarrett" <notifications@github.com>:

**Comment by daxlab** [comment] 2016-02-28 17:56
the problem is with ```universal-analytics```

**Comment by wb9688** [comment] 2016-03-13 08:02
@jakejarrett @weblancaster I made [a patch](https://gist.github.com/wb9688/e105d5179583e0294815) for the `universal-analytics` problem...

**Comment by rahilwazir** [comment] 2016-03-15 12:03
Same issue, here is the stack trace:

```
[15916:0315/165907:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[15916:0315/165911:ERROR:nw_shell.cc(336)] Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/tmp/.org.chromium.Chromium.QbAsbQ/node_modules/universal-analytics/lib/index.js:2:13)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[15916:0315/165911:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'async'", source: module.js (329)
[15916:0315/165911:INFO:CONSOLE(13)] ""User is saved"", source: file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/system/userConfig.js (13)
[15916:0315/165911:INFO:CONSOLE(16)] ""Download the React DevTools for a better development experience: https://fb.me/react-devtools"", source: file:///tmp/.org.chromium.Chromium.QbAsbQ/dist/bundle.js (16)
[15916:0315/165913:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'visitor' of undefined
    at file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/app.js:102:20
    at Object.e [as invoke] (file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:37:96)
    at file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:38:454
    at s (file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:7:302)
    at Ob (file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:38:433)
    at d (file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:17:350)
    at Object.sc [as bootstrap] (file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/vendor/angular.min.1.3.8.js:18:153)
    at file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/system/authentication.js:60:17
[15916:0315/165913:INFO:CONSOLE(102)] "Uncaught TypeError: Cannot read property 'visitor' of undefined", source: file:///tmp/.org.chromium.Chromium.QbAsbQ/public/js/app.js (102)
[15947:0315/170020:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
```

**Comment by wb9688** [comment] 2016-03-15 14:35
@rahil download the source, apply my patch and compile it...
Op 15 mrt. 2016 13:04 schreef "Rahil" <notifications@github.com>:

**Comment by rahilwazir** [comment] 2016-03-15 14:53
@wb9688 Why don't you create PR to this repo?

**Comment by wb9688** [comment] 2016-03-15 15:02
@rahil I wanted to do that, but I was on vacation and the firewall blocked
SSH...
Op 15 mrt. 2016 15:53 schreef "Rahil" <notifications@github.com>:

**Comment by rahilwazir** [comment] 2016-03-15 15:39
Ok :smile: don't forget to merge your patch here later.

**Comment by rahilwazir** [comment] 2016-03-20 09:38
@wb9688 I'm getting error applying patch on my Windows machine, worked fine on my Linux machine.

```
$ git am 0001-Fixed-GA.patch
Applying: Fixed GA
error: patch failed: app/public/js/app.js:98
error: app/public/js/app.js: patch does not apply
Patch failed at 0001 Fixed GA
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by Recydywa** [comment] 2016-03-26 18:35
Todays release v0.6.3 resolved the issue for me.

**Comment by rahilwazir** [comment] 2016-03-26 22:43
@Recydywa Not sure, updated to the latest release still having same issue as OP on Windows.

**Comment by weblancaster** [comment] 2016-03-26 22:46
@rahilwazir can you describe your workflow please and what account (facebook or google?) you are using.

**Comment by rahilwazir** [comment] 2016-03-27 08:33
- I clone the latest master
- grunt build (succeed)
- Run win32 binary
- Login through SoundCloud. (no SSO)
- Stuck at authenticating screen

Windows 10 x64

**Comment by rahilwazir** [comment] 2016-03-28 11:36
@weblancaster Latest release worked fine on Linux x64 without applying the [patch above](https://github.com/Soundnode/soundnode-app/issues/524#issuecomment-195911605)

**Comment by rahilwazir** [comment] 2016-03-28 11:48
Damn! Sorry ignore my previous comment.
Linux x64 also causing the same problem.

```
$ ./Soundnode 
[26057:0328/164057:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[26057:0328/164058:ERROR:nw_shell.cc(336)] Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/tmp/.org.chromium.Chromium.lOT1fI/node_modules/universal-analytics/lib/index.js:2:13)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[26057:0328/164058:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'async'", source: module.js (329)
[26057:0328/164058:INFO:CONSOLE(13)] ""User is saved"", source: file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/system/userConfig.js (13)
[26057:0328/164058:INFO:CONSOLE(16)] ""Download the React DevTools for a better development experience: https://fb.me/react-devtools"", source: file:///tmp/.org.chromium.Chromium.lOT1fI/dist/bundle.js (16)
[26057:0328/164100:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'visitor' of undefined
    at file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/app.js:102:20
    at Object.e [as invoke] (file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:37:96)
    at file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:38:454
    at s (file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:7:302)
    at Ob (file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:38:433)
    at d (file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:17:350)
    at Object.sc [as bootstrap] (file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/vendor/angular.min.1.3.8.js:18:153)
    at file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/system/authentication.js:60:17
[26057:0328/164100:INFO:CONSOLE(102)] "Uncaught TypeError: Cannot read property 'visitor' of undefined", source: file:///tmp/.org.chromium.Chromium.lOT1fI/public/js/app.js (102)
^C
rw@rw [linux64]# [26079:0328/164352:WARNING:x11_util.cc(1490)] X error received: serial 89205, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
```

Nor the [patch above](https://github.com/Soundnode/soundnode-app/issues/524#issuecomment-195911605) is being applied now

**Comment by rahilwazir** [comment] 2016-03-28 12:08
Arrgghh :sob: , the [build](http://www.soundnodeapp.com/downloads/linux64/Soundnode-App.zip) from main website is working fine.

**Comment by weblancaster** [comment] 2016-03-28 17:24
Ah ok can you tell me the node version and the npm version you are running please @rahilwazir

**Comment by rahilwazir** [comment] 2016-03-29 06:55
@weblancaster 

node: v5.9.1
npm: v3.7.3

**Comment by weblancaster** [comment] 2016-03-29 15:31
Ah have you tried downgrade to npm < 3 @rahilwazir ?

**Comment by jakejarrett** [comment] 2016-03-29 20:44
@rahilwazir Could you try using npm with [nvm](https://github.com/creationix/nvm) if you aren't already? That should make it easy to test if its npm breaking or not

**Comment by weblancaster** [comment] 2016-03-29 20:59
I'm positive that the issue is because of the use of NPM 3 so downgrading will be a goo try.

**Comment by rahilwazir** [comment] 2016-03-30 06:48
@jakejarrett @weblancaster Yes, downgraded to npm 2x and it works.
Can you tell me why that happen?

**Comment by jakejarrett** [comment] 2016-03-30 07:54
@rahilwazir npm changed how dependencies were being handled/installed
[differences between npm3 & npm2 dependencies](https://docs.npmjs.com/how-npm-works/npm3)

**Comment by weblancaster** [comment] 2016-03-30 14:30
Great.. closing this issue.

**Closed by weblancaster** 2016-03-30 14:30 UTC

**Comment by wb9688** [comment] 2016-04-05 17:30
@jakejarrett you can use npm's old behaviour with the `--legacy-bundling` flag, I already changed the wiki to include that
