### ISSUE TITLE
Rate Limiting (Error 429)

### ISSUE THREAD

**Issue by otisscott** [Soundnode/soundnode-app#987] opened 2017-05-23 05:21 UTC
I just downloaded you program for windows and it is refusing to play anymusic. I have some experience with the SoundCloud API, and when I checked the dev tools console I noticed that it was throwing a 429 rate limit error. Is there any way to fix that or am I SOL?

Edit: If there isn't a global fix, I do have my own API key, I just want to know how I can replace yours with mine?

**Comment by wb9688** [comment] 2017-05-23 05:23
This is yet another duplicate of #802, where I've posted a solution.

**Comment by otisscott** [comment] 2017-05-23 05:50
Where is the actual answer to the issue in that cluster f*ck and am I going to have to compile the project myself?

**Comment by wb9688** [comment] 2017-05-23 06:24
https://github.com/soundnode/soundnode-app/issues/802#issuecomment-261705999

**Closed** 2017-05-25 18:02 UTC

**Comment by weblancaster** [comment] 2017-05-25 18:10
@otisscott there is no concrete solution so far, people has explored different ways.

Solution 1: Request Soundcloud a key so you can host https://github.com/Soundnode/sc-oauth and use your own `id` and `secret`
Solution 2: try using soundcloud `id` and `secret` with @wb9688 suggestion in #802
