### ISSUE TITLE
[Feature Suggestion] Arbitrary seek by clicking on seekbar

### ISSUE THREAD

**Issue by swrobel** [Soundnode/soundnode-app#847] opened 2016-08-13 00:12 UTC
On the Soundcloud website, you can click on any arbitrary spot on the seekbar and it will skip to that part of the track. Soundnode requires you to click & drag the progress indicator. This is much less convenient than just being able to click anywhere to seek.

https://sendvid.com/ghoqupev

Version: Release 0.6.5 for MacOS
Downloaded from: homebrew-cask
OS: MacOS 10.12 PB4

**Comment by Pitros** [comment] 2016-08-13 10:39
That's just a bug and it needs to be fixed.

**Comment by weblancaster** [comment] 2016-08-14 17:12
Not a bug @Pitros that's how I coded to be at the beginning.

We can add this feat though.

**Comment by Pitros** [comment] 2016-08-24 17:38
@swrobel, @weblancaster on Windows click to seek track always worked, and still works fine.

https://dl.dropboxusercontent.com/s/z0jwbtww3retsik/2016-08-24_19-35-28.mp4

**Comment by wb9688** [comment] 2016-08-24 18:02
It works fine on both my Windows and Linux machine…

**Comment by zimme** [comment] 2016-10-26 20:20
I have this problem too on my MBP, macOS Sierra, installed with homebrew.

**Comment by zimme** [comment] 2016-10-26 20:45
I had a look at the code, and can see that this is taken care of in [here](https://github.com/Soundnode/soundnode-app/blob/72580b8f871ca05132e04a2c872de9c36c1f2a36/app/public/js/common/playerService.js#L352).
I can't really say I'm familiar with angular and the way you're using the events here,
but if I get some time over this weekend I'll try and see if I can't add support for click to seek.

**Comment by weblancaster** [comment] 2016-11-09 22:17
This is implemented but not released yet.. closing down to keep the issues clean

**Closed by weblancaster** 2016-11-09 22:17 UTC
Labels: feature
