### ISSUE TITLE
[Bug] Queue error on shuffle mode

### ISSUE THREAD

**Issue by phanrandy31** [Soundnode/soundnode-app#650] opened 2016-02-15 19:26 UTC

**Comment by weblancaster** [comment] 2016-02-19 15:52
Could you explain the issue please @phanrandy31

**Comment by dgattey** [comment] 2016-04-11 08:36
Looks like a duplicate of #683

**Comment by weblancaster** [comment] 2016-04-11 15:20
Very possibly @dgattey so for that reason and for no new updates I'm closing this issue.

**Closed by weblancaster** 2016-04-11 15:20 UTC
