### ISSUE TITLE
packagecloud repository cannot be retrieved

### ISSUE THREAD

**Issue by FreshestJamz** [Soundnode/soundnode-app#1085] opened 2018-09-13 01:39 UTC
the packagecloud repository cannot be retrieved by my terminal 

`~# curl -s https://packagecloud.io/install/repositories/JonasGroeger/soundnode/script.deb.sh | sudo bash
Detected operating system as Kali/kali-rolling.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/JonasGroeger_soundnode.list...curl: (22) The requested URL returned error: 404 Not Found

Unable to download repo config from: https://packagecloud.io/install/repositories/JonasGroeger/soundnode/config_file.list?os=Kali&dist=kali-rolling&source=script`

showing that the packagecloud link on the website is no longer functional, and if I download off the old packagecloud repo directly it will install, however the install is broken, thinking that it needs an update that does not exist and not being able to play any music ("o no something went wrong I cant play that") even after clearing system info, relogging, and restarting the app, any help

--running kali linux--

**Comment by jakejarrett** [comment] 2018-09-13 11:41
Closing as a duplicate of #1075

**Closed by jakejarrett** 2018-09-13 11:41 UTC
