### ISSUE TITLE
[Feature] Option to choose audio device

### ISSUE THREAD

**Issue by Himijimmy** [Soundnode/soundnode-app#480] opened 2016-01-06 20:54 UTC
Please create an option to configure the audio device which I want to use, so it would be easy to use the player for music bots.

**Comment by DJmRek** [comment] 2016-02-05 22:50
This woud be a very usefull feature! I support this feature-request!

**Comment by Pitros** [comment] 2016-02-05 23:47
Duplicate of #262.

**Closed by Pitros** 2016-02-05 23:47 UTC
