### ISSUE TITLE
cant play any tracks.

### ISSUE THREAD

**Issue by ExileEditing** [Soundnode/soundnode-app#997] opened 2017-06-21 00:21 UTC
http://prntscr.com/fm7vvy
cant play any tracks. I just downloaded this

**Comment by MightyRufo** [comment] 2017-06-22 05:11
I second this and I just found out about it today.

**Comment by wb9688** [comment] 2017-06-22 05:13
This is yet another duplicate of #802, which is also the place where I've
posted a temporarily solution.

**Closed** 2017-06-22 06:10 UTC

**Comment by MightyRufo** [comment] 2017-06-22 07:17
Why is the main download link not updated with the fix?

**Comment by weblancaster** [comment] 2017-06-22 07:32
@MightyRufo You can look all the away in the bottom of #802 that I explain one of the ways around it. Another way is running @wb9688 script.

**Comment by wb9688** [comment] 2017-06-22 08:20
@MightyRoof: Because it isn't an official build. When I've time to
correctly fix it, I'll contribute some changes and a new official build
will be released.

---

@weblancaster: Couldn't you add a comment template stating something like
the following?

Please check if your issue is already reported. If you can't play tracks,
please take a look at #802.

---

@weblancaster: Since I've no experience with AngularJS (1), could you
explain (or link to) how I can add a page (for logging in)?
