### ISSUE TITLE
Bad 0.6.5 build on linux, missing mpris.

### ISSUE THREAD

**Issue by Mar-tin-W** [Soundnode/soundnode-app#830] opened 2016-07-24 10:37 UTC
Package: soundnode 64bit linux

**Comment by Mar-tin-W** [comment] 2016-07-24 10:44
![screenshot from 2016-07-24 12 44 03](https://cloud.githubusercontent.com/assets/20623262/17083313/5c02414e-519c-11e6-92b5-f6845629fbdd.png)

**Comment by Mar-tin-W** [comment] 2016-07-24 10:47
same thing with likes, tracks, playlists and top 50
(newest version)

**Comment by Pitros** [comment] 2016-07-24 13:52
It looks like tracks aren't loading at all. Please open dev tools (ctrl/cmd + /) and show us console tab.

**Comment by Mar-tin-W** [comment] 2016-07-24 17:46
Sorry I'm new to github. 
What is dev tools and where can I get it?

**Comment by Pitros** [comment] 2016-07-24 17:47
Press ctrl + / on Soundnode.

**Comment by Mar-tin-W** [comment] 2016-07-24 17:51
![screenshot from 2016-07-24 19 51 08](https://cloud.githubusercontent.com/assets/20623262/17085430/027a0436-51d8-11e6-869f-3f7ea0e24ab1.png)

**Comment by Pitros** [comment] 2016-07-24 17:53
Can you expand those, and show bit more info. As well please try clearing data (from settings menu) and login once again to soundnode.

**Comment by Mar-tin-W** [comment] 2016-07-24 17:58
![screenshot from 2016-07-24 19 58 34](https://cloud.githubusercontent.com/assets/20623262/17085468/08dbfe1e-51d9-11e6-830b-2d5604e36d2b.png)

**Comment by Pitros** [comment] 2016-07-24 18:00
Ok, so it looks like there's problem with mpris @jakejarrett or linux build has problems.

**Comment by Mar-tin-W** [comment] 2016-07-24 18:01
the last version worked just fine.

**Comment by jakejarrett** [comment] 2016-07-25 07:53
I'm guessing this is due to the build process being different on Windows/Mac as they actually can not build dbus unless we include the headers.

I'll look into this more and get a solution ready asap.

**Comment by SirCmpwn** [comment] 2016-07-25 20:36
Can reproduce.

**Comment by doctorcolossus** [comment] 2016-07-28 22:23
Ditto. Please let me know if I can assist with further information.

**Comment by CodyMKW** [comment] 2016-07-31 03:07
same for me on Ubuntu MATE 16.04.1 LTS

**Comment by SKUndef** [comment] 2016-08-09 08:10
I'm experiencing the same bug. In the meantime, where we can get a build of the previous version 0.6.4? Thanks for your work.

**Comment by CodyMKW** [comment] 2016-08-09 12:40
@SKUndef https://github.com/Soundnode/soundnode-app/releases/tag/0.6.4

**Comment by SKUndef** [comment] 2016-08-09 12:59
@CodyMKW Thanks, but souce code needs to be compiled. I could do it of couse, but what i'm looking for is a runnable archive like the 0.6.5 one downloadable at http://www.soundnodeapp.com/downloads/linux64/Soundnode.zip. Thanks!

**Comment by wb9688** [comment] 2016-08-09 13:08
@SKUndef you can download from the PPA…

**Comment by SKUndef** [comment] 2016-08-09 13:19
@wb9688 I'm not a Debian based distro user. No problem, I will either compile the source or wait for next release. Thanks

**Comment by CodyMKW** [comment] 2016-08-09 14:58
@SKUndef try this might work https://web.archive.org/web/20160609101205/http://www.soundnodeapp.com/downloads/linux64/Soundnode-App.zip

**Comment by SKUndef** [comment] 2016-08-09 15:10
@CodyMKW Nice resource, thank you very much! It's 0.6.2 version indeed, but it's enough for now ;)

**Comment by jakejarrett** [comment] 2016-08-11 21:14
@weblancaster the only interim fix I can think of is building on Linux. I was unable to find a solution that would work across all platforms

**Comment by wb9688** [comment] 2016-08-11 21:23
@jakejerett But then you couldn't build 32-bit Linux version on 64-bit
Linux, so that's add more complexity…

**Comment by jakejarrett** [comment] 2016-08-11 21:53
@wb9688 from memory, you should be able to build 32bit from 64bit, you just wouldn't be able to run it.

**Comment by wb9688** [comment] 2016-08-12 06:31
@jakejerett You can indeed build it on a 64-bit machine, but not run it on
a 32-bit machine. Maybe we could just drop the 32-bit Linux build if it
isn't used much (@weblancaster ???), you made a 32-bit Linux build because
I was using 32-bit machines at that time…

**Comment by SKUndef** [comment] 2016-08-12 09:38
If the bug is entirely about the MPRIS support, why not drop it while seeking for a solution?

**Comment by Pitros** [comment] 2016-08-12 10:17
So there are two ways to solve it - drop MPRIS support or build linux releases on linux machines - we can use 32/64bit VMs for 32 and 64 bit versions or if someone is able to cross-compile for 32 bits on 64bit machine only 64 bit machine would be needed.

**Comment by wb9688** [comment] 2016-08-12 10:22
@pjotr My idea would be to set up Vagrant to compile for 32- and 64-bit
Linux…

**Comment by jakejarrett** [comment] 2016-08-17 09:27
@Soundnode/core-team there's currently work being done on porting mpris-service over to purely JS interface, I think the best bet would be to remove/disable the functionality and reinstate it once it's ready to be used.

Related-
emersion/mpris-service#6

**Comment by nickjbyrne** [comment] 2016-09-08 09:19
Any ETA on a fix for this?

**Closed** 2016-09-14 10:32 UTC
Labels: bug, Important, in progress

**Comment by pereyrdi** [comment] 2017-04-24 13:37
Same problem here!
I just download last version and same issue occurs. (Mint 18.1 Xfce 64bits.)

**Comment by weblancaster** [comment] 2017-04-24 16:20
@nickjbyrne @pereyrdi this was fixed around jan/feb but I haven't released a new version yet since. I just need to make time to build a pre-realese test it and then release to the users.

**Comment by wb9688** [comment] 2017-04-24 16:27
@weblancaster: AFAIK there was never a problem, at least not when I built
it on my machine, but there was a problem with the official builds.

**Comment by jakejarrett** [comment] 2017-04-29 11:14
@weblancaster @wb9688 The issue was that the mpris module can't be built out of the box on windows/mac osx (Making linux a hard dependency for building with mpris support).

Ideally, a Javascript only solution would be better ([referenced here](https://github.com/Soundnode/soundnode-app/issues/830#issuecomment-240360653)) but these have to be fixed in [node-dbus](https://github.com/sidorares/node-dbus).
