### ISSUE TITLE
App closing randomly

### ISSUE THREAD

**Issue by DeckardPain** [Soundnode/soundnode-app#197] opened 2015-01-12 06:26 UTC
Click play on a track and it plays until the end and then closes immediately. No error message at all or anything.

Click play on a different track and it closes without playing.

**Comment by weblancaster** [comment] 2015-01-12 15:26
Thanks for the input @DeckardPain I will take a look on that but can you tell me which platform are you? Win/Mac/Linux? and are you using the latest version of Soundnode?

**Comment by jasonscholefield** [comment] 2015-01-12 16:39
No problem.

I'm on Windows 7 with what I'm guessing is the most recent version (0.5). When I was having the problem I checked the version number to make sure I was up to date but didn't see a current version number on the http://www.soundnodeapp.com/ page so I checked here and it said 0.5 was the current version.

**Comment by jakehh** [comment] 2015-01-17 11:23
If you can run this in console (ctrl + /), it should output an error and prevent it from instantly closing & output what caused the error.

```javascript
process.on('uncaughtException', function (err) {
	window.console.error(err, err.stack);
	alert(err);
});
```

**Comment by PEPZ** [comment] 2015-01-22 01:29
I have the same issue. I am on Windows 8.1, app version 0.5.1 (same issue existed on 0.5.0). I tried jakehh's suggestion, but the app closes also closing the console window. 

Here are a few tracks that instantly close the app:
https://soundcloud.com/mixmag-1/exclusive-gina-turner-b2b-laidback-luke-holy-ship-mix
https://soundcloud.com/redbullmusicacademy/haioka-laura-j-martin-summer-1
https://soundcloud.com/cascaderecords/out-of-the-cloud-by-julien-mier-out-now

**Comment by jakehh** [comment] 2015-01-22 09:11
Hey Pepz,

Try this one (It will prevent the app from closing so you will need task manager open)

```javascript
var gui = require('nw.gui');
var win = gui.Window.get();

win.on('close', function() {
    alert("Error");
    win.focus();
});

process.on('uncaughtException', function (err) {
    window.console.error(err, err.stack);
    alert(err);
});

```

Sorry, i can't test this code atm, It *should* work.

**Comment by PEPZ** [comment] 2015-01-22 11:01
Thanks for the input @jakehh. Sadly this code also doesn't help. The app closes on the tracks previously mentioned and the app also closes when I press the exit button (no need to use task manager for closing)

**Comment by weblancaster** [comment] 2015-01-22 15:26
Hey @PEPZ and @jakehh I'm going to do some tests this weekend and see if I can come up with something to fix it.

Let me know if you guys figured out something.

Thanks for the help.

**Comment by PEPZ** [comment] 2015-01-31 23:39
Hi, @weblancaster did you manage to trace what's causing the bug? Thanks

**Comment by weblancaster** [comment] 2015-02-02 17:35
Hey @PEPZ I still trying to figure out what is happening because I can't replicate on my Mac.. I was able to listen to all those songs without any problem.

**Comment by DeckardPain** [comment] 2015-02-02 17:46
I'll test it out later when I'm off work with what was posted above and get back do you.

**Comment by weblancaster** [comment] 2015-02-02 18:41
Sounds good @DeckardPain

**Comment by DeckardPain** [comment] 2015-02-04 04:23
Didn't fix it for me.

First track in the window plays, but when I try to choose another track to play it just crashes immediately.

**Comment by jakehh** [comment] 2015-02-04 12:33
If you listed the information in a gist that would be great, i can give it a look tomorrow.

**Comment by weblancaster** [comment] 2015-02-04 15:34
I'm going to update to the latest version of nw.js this weekend to see if solves the issue.

Untill then.. thanks for the help everybody.

**Comment by weblancaster** [comment] 2015-02-06 18:54
This seems like a Windows issue.. so I will focus on that.

**Comment by PEPZ** [comment] 2015-02-20 09:34
Hi, @weblancaster @jakejarrett are You finding any lead on the issue? I did the latest update and sadly the issue still persists. I'm not much of a programmer, but I can do some testing if You don't have access to a Windows PC.

**Comment by weblancaster** [comment] 2015-02-20 15:03
Hey @PEPZ I haven't had the chance to test and update the audio codec and test to see if this will fix it..
And find the right audio codecs version it's sort of a pain besides the regression test I need to do.

I'm planning to do this very soon.

**Comment by PEPZ** [comment] 2015-04-10 09:32
@weblancaster Nothing on this yet?

**Comment by jakejarrett** [comment] 2015-04-10 10:49
@PEPZ @weblancaster It doesn't fully close, the process continues in powershell, Not too sure what's causing it since it's not outputting any errors. Could be an issue with the Node-webkit libraries?

**Comment by weblancaster** [comment] 2015-04-10 16:52
Yes it could be something related to nw.js

It never happened to me to be honest, but multiple people complained that this happened to them a couple of times with specific tracks.

I tried those tracks they had issues but nothing happened here.

I'm updating the core nw.js at this moment.. let's hope this is going to fix it @PEPZ @jakejarrett

**Comment by PEPZ** [comment] 2015-04-18 13:18
Thrilled to hear about the fixes! Thanks a lot for having a look into this @Pitros! @weblancaster , when is the planned update with the fix integrated? Thanks!

**Comment by weblancaster** [comment] 2015-05-21 19:56
Sorry the delay.. but I released the new version finally!

@DeckardPain  @jasonscholefield @jakejarrett @PEPZ @jasonscholefield

**Closed by weblancaster** 2015-05-21 19:56 UTC
