### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by fluse** [Soundnode/soundnode-app#932] opened 2016-12-22 22:07 UTC
as a user of your app, i would select a specific time on the track timeline.

![pointing](https://cloud.githubusercontent.com/assets/6527681/21441974/5ae1d3c6-c89b-11e6-9a18-e5f3ec24f297.png)

maybe the height of line can be increase on hover, to get a better experience for selecting ;-)

**Comment by wb9688** [comment] 2016-12-23 05:29
You can already click there, at least on Linux and Windows…

**Comment by victor-lin** [comment] 2016-12-24 00:42
Clicking and dragging the playhead works as intended, but clicking anywhere other than the playhead does not let the user jump to that point in the song.
(running macOS)

**Comment by weblancaster** [comment] 2017-01-10 15:50
I have fixed in the latest version and will be released soon.

**Closed by weblancaster** 2017-01-10 15:50 UTC
